/**
 * Lightweight path index for AI/dev navigation. Not imported by the app at runtime.
 * Keep in sync with code-map.md when modules move or names change.
 */
export const codeMap = {
  core: {
    transactionAnalytics: 'src/lib/transaction-analytics.ts',
    transactionFlow: 'src/lib/transaction-flow.ts',
    debugTransactionFlow: 'src/lib/debug-transaction-flow.ts',
    spendingInsights: 'src/lib/spending-insights.ts',
    recurringTransactions: 'src/lib/recurring-transactions.ts',
    financialHealthScore: 'src/lib/financial-health-score.ts',
    categorySuggestion: 'src/lib/category-suggestion.ts',
    transactionFilters: 'src/lib/transaction-filters.ts',
    transactions: 'src/lib/transactions.ts',
    sensitiveInputs: 'src/lib/validation/sensitive-inputs.ts',
    authedApi: 'src/lib/authed-api.ts',
    supabaseServer: 'src/lib/supabase-server.ts',
    supabaseClient: 'src/lib/supabase.ts',
    csvTransactions: 'src/lib/csv-transactions.ts',
    parseTransactionsFromText: 'src/lib/parse-transactions-from-text.ts',
    taxEstimator: 'src/lib/tax-estimator.ts',
    rentVsBuy: 'src/lib/rent-vs-buy.ts',
    creditScoreSim: 'src/lib/credit-score-sim.ts',
    decisionEngine: 'src/lib/decision-engine.ts',
  },
  pages: {
    rootLayout: 'src/app/layout.tsx',
    landing: 'src/app/page.tsx',
    login: 'src/app/login/page.tsx',
    signup: 'src/app/signup/page.tsx',
    guide: 'src/app/guide/page.tsx',
    appLayout: 'src/app/(app)/layout.tsx',
    dashboard: 'src/app/(app)/dashboard/page.tsx',
    settings: 'src/app/(app)/settings/page.tsx',
    toolsIndex: 'src/app/(app)/tools/page.tsx',
    toolCreditScore: 'src/app/(app)/tools/credit-score/page.tsx',
    toolTax: 'src/app/(app)/tools/tax-estimator/page.tsx',
    toolDecision: 'src/app/(app)/tools/decision-engine/page.tsx',
    toolRentVsBuy: 'src/app/(app)/tools/rent-vs-buy/page.tsx',
    toolImport: 'src/app/(app)/tools/import-transactions/page.tsx',
  },
  api: {
    transactionsPost: 'src/app/api/transactions/route.ts',
    transactionsPatch: 'src/app/api/transactions/[id]/route.ts',
    transactionsBulkDelete: 'src/app/api/transactions/bulk/route.ts',
    transactionsImport: 'src/app/api/transactions/import/route.ts',
    parsePdf: 'src/app/api/parse-pdf/route.ts',
    profileBudget: 'src/app/api/profile/budget/route.ts',
    profileCurrency: 'src/app/api/profile/currency/route.ts',
    authAttempt: 'src/app/api/auth/attempt/route.ts',
  },
  dashboardComponents: [
    'src/components/dashboard/SummaryCard.tsx',
    'src/components/dashboard/NetSavingsCard.tsx',
    'src/components/dashboard/MonthlyBudgetCard.tsx',
    'src/components/dashboard/FinancialHealthCard.tsx',
    'src/components/dashboard/FinancialInsights.tsx',
    'src/components/dashboard/CategoryPieChart.tsx',
    'src/components/dashboard/SpendingBarChart.tsx',
    'src/components/dashboard/TransactionEditModal.tsx',
  ],
  layout: [
    'src/components/layout/AppShell.tsx',
    'src/components/layout/AppNavbar.tsx',
    'src/components/layout/LandingNavbar.tsx',
    'src/components/layout/BrandLogoLink.tsx',
  ],
  toolsClients: [
    'src/components/tools/ToolPageShell.tsx',
    'src/components/tools/CreditScoreSimClient.tsx',
    'src/components/tools/TaxEstimatorClient.tsx',
    'src/components/tools/DecisionEngineClient.tsx',
    'src/components/tools/RentVsBuyClient.tsx',
    'src/components/tools/ImportTransactionsClient.tsx',
    'src/components/tools/PdfBankStatementUpload.tsx',
  ],
  contexts: ['src/contexts/auth-context.tsx', 'src/contexts/currency-context.tsx'],
  migrationsGlob: 'supabase/migrations/*.sql',
} as const

export type CodeMap = typeof codeMap
