-- AI insights cache: store one set of AI-generated insights per user per calendar month.
-- Month key format: 'YYYY-MM'. The unique constraint prevents duplicates; upsert on conflict.
create table if not exists public.ai_insights_cache (
  id          uuid        primary key default gen_random_uuid(),
  user_id     uuid        not null references auth.users(id) on delete cascade,
  month_key   text        not null,
  insights    jsonb       not null,
  created_at  timestamptz not null default now(),
  constraint ai_insights_cache_user_month unique (user_id, month_key)
);

comment on table  public.ai_insights_cache          is 'Cached AI-generated financial insight strings per user per calendar month.';
comment on column public.ai_insights_cache.month_key is 'Calendar month in YYYY-MM format (server local, UTC).';
comment on column public.ai_insights_cache.insights  is 'JSON array of insight strings generated by the AI model.';

alter table public.ai_insights_cache enable row level security;

create policy "Users can read own insights cache"
  on public.ai_insights_cache for select
  using (auth.uid() = user_id);

create policy "Users can insert own insights cache"
  on public.ai_insights_cache for insert
  with check (auth.uid() = user_id);

create policy "Users can update own insights cache"
  on public.ai_insights_cache for update
  using (auth.uid() = user_id);
